{application,cf,
             [{description,"Terminal colour helper"},
              {vsn,"0.2.2"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {env,[]},
              {modules,[cf,cf_term]},
              {maintainers,["Heinz N. Gies <heinz@project-fifo.net>"]},
              {licenses,["MIT"]},
              {links,[{"github","https://github.com/project-fifo/cf"}]}]}.
